In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('JC-201905-citibike-tripdata.csv')
df1.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,311,2019-05-01 00:07:36.4670,2019-05-01 00:12:47.6350,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,29224,Subscriber,1988,1
1,538,2019-05-01 00:08:29.2840,2019-05-01 00:17:27.9410,3681,Grand St,40.715178,-74.037683,3203,Hamilton Park,40.727596,-74.044247,26170,Subscriber,1974,1
2,178,2019-05-01 00:39:36.4750,2019-05-01 00:42:34.9640,3638,Washington St,40.724294,-74.035483,3639,Harborside,40.719252,-74.034234,29517,Subscriber,1988,1
3,317,2019-05-01 01:24:28.0220,2019-05-01 01:29:45.5730,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,29606,Subscriber,1986,2
4,354,2019-05-01 01:54:39.6660,2019-05-01 02:00:34.1750,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,26224,Customer,1986,2

In [3]:
df2 = pd.read_csv('JC-201904-citibike-tripdata.csv')
df2.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,107,2019-04-01 07:48:04.7540,2019-04-01 07:49:52.3590,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29536,Subscriber,1966,1
1,493,2019-04-01 12:41:09.6540,2019-04-01 12:49:23.0290,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,26191,Customer,1990,1
2,512,2019-04-01 14:27:07.9400,2019-04-01 14:35:40.9370,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29302,Subscriber,1987,2
3,196,2019-04-01 15:07:38.1510,2019-04-01 15:10:54.6260,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,26220,Subscriber,1989,1
4,463,2019-04-01 16:19:24.6940,2019-04-01 16:27:08.6450,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,26228,Subscriber,1995,1

In [4]:
df3 = pd.read_csv('JC-201903-citibike-tripdata.csv')
df3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,306,2019-03-01 06:47:08.2110,2019-03-01 06:52:14.7150,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26272,Subscriber,1989,1
1,123,2019-03-01 07:30:53.0220,2019-03-01 07:32:56.7770,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26192,Subscriber,1966,1
2,328,2019-03-01 08:18:30.4030,2019-03-01 08:23:59.0590,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,26226,Subscriber,1971,2
3,95,2019-03-01 11:04:47.2020,2019-03-01 11:06:22.8130,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26204,Subscriber,1985,1
4,169,2019-03-01 11:51:29.4170,2019-03-01 11:54:19.2120,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29449,Subscriber,1971,1

In [5]:
df4 = pd.read_csv('JC-201902-citibike-tripdata.csv')
df4.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,142,2019-02-01 15:35:02.0820,2019-02-01 15:37:24.1360,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29677,Subscriber,1963,1
1,223,2019-02-01 17:00:46.8900,2019-02-01 17:04:30.5500,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,26234,Subscriber,1992,2
2,106,2019-02-01 17:08:01.3260,2019-02-01 17:09:47.4400,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29588,Subscriber,1960,1
3,370,2019-02-01 17:09:31.2100,2019-02-01 17:15:41.6550,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,29250,Subscriber,1976,1
4,315,2019-02-01 17:19:53.2490,2019-02-01 17:25:09.1400,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,29586,Subscriber,1980,1

In [6]:
df5 = pd.read_csv('JC-201901-citibike-tripdata.csv')
df5.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0

In [7]:
df6 = pd.read_csv('JC-201812-citibike-tripdata.csv')
df6.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,170,2018-12-01 00:03:53.3860,2018-12-01 00:06:43.7160,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,26261,Subscriber,1975,1
1,172,2018-12-01 00:47:13.7340,2018-12-01 00:50:05.8160,3183,Exchange Place,40.716247,-74.033459,3481,York St,40.716490,-74.041050,26175,Subscriber,1988,1
2,247,2018-12-01 00:48:57.6960,2018-12-01 00:53:05.6780,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29255,Subscriber,1990,1
3,406,2018-12-01 01:33:53.6630,2018-12-01 01:40:39.7480,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29275,Subscriber,1995,1
4,354,2018-12-01 06:26:52.5120,2018-12-01 06:32:46.5170,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,29658,Subscriber,1976,1

In [8]:
df7 = pd.read_csv('JC-201811-citibike-tripdata.csv')
df7.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1188,2018-11-01 06:32:27.5190,2018-11-01 06:52:15.9140,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,33662,Customer,1969,0
1,278,2018-11-01 07:14:31.8680,2018-11-01 07:19:10.2610,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29254,Subscriber,1963,1
2,115,2018-11-01 07:33:17.1920,2018-11-01 07:35:12.2830,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,33607,Subscriber,1966,1
3,155,2018-11-01 08:20:10.9320,2018-11-01 08:22:46.7050,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29222,Subscriber,1975,2
4,82,2018-11-01 08:35:02.7850,2018-11-01 08:36:25.1840,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29678,Subscriber,1975,1

In [9]:
citibike_2018_2019 = pd.concat([df1, df2, df3, df4, df5, df6, df7])
citibike_2018_2019

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,311,2019-05-01 00:07:36.4670,2019-05-01 00:12:47.6350,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,29224,Subscriber,1988,1
1,538,2019-05-01 00:08:29.2840,2019-05-01 00:17:27.9410,3681,Grand St,40.715178,-74.037683,3203,Hamilton Park,40.727596,-74.044247,26170,Subscriber,1974,1
2,178,2019-05-01 00:39:36.4750,2019-05-01 00:42:34.9640,3638,Washington St,40.724294,-74.035483,3639,Harborside,40.719252,-74.034234,29517,Subscriber,1988,1
3,317,2019-05-01 01:24:28.0220,2019-05-01 01:29:45.5730,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,29606,Subscriber,1986,2
4,354,2019-05-01 01:54:39.6660,2019-05-01 02:00:34.1750,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,26224,Customer,1986,2
5,357,2019-05-01 01:54:43.6300,2019-05-01 02:00:41.0210,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,29541,Customer,1986,1
6,138,2019-05-01 02:25:04.8320,2019-05-01 02:27:23.0580,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29280,Subscriber,1979,1
7,299,2019-05-01 03:50:09.1180,2019-05-01 03:55:08.8850,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29479,Subscriber,1987,1
8,296,2019-05-01 04:44:27.7800,2019-05-01 04:49:24.4570,3203,Hamilton Park,40.727596,-74.044247,3202,Newport PATH,40.727224,-74.033759,29554,Subscriber,1967,1
9,811,2019-05-01 04:55:48.9470,2019-05-01 05:09:20.2810,3207,Oakland Ave,40.737604,-74.052478,3185,City Hall,40.717733,-74.043845,29666,Subscriber,1984,2
10,293,2019-05-01 05:06:54.6420,2019-05-01 05:11:48.0680,3272,Jersey & 3rd,40.723332,-74.045953,3638,Washington St,40.724294,-74.035483,29674,Subscriber,1964,1
11,287,2019-05-01 05:15:41.5460,2019-05-01 05:20:29.0360,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,29449,Subscriber,1973,2
12,268,2019-05-01 05:22:29.3550,2019-05-01 05:26:57.7180,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,29449,Subscriber,1990,1
13,234,2019-05-01 05:23:58.9310,2019-05-01 05:27:53.2280,3278,Monmouth and 6th,40.725685,-74.048790,3186,Grove St PATH,40.719586,-74.043117,29614,Subscriber,1985,1
14,156,2019-05-01 05:27:32.1140,2019-05-01 05:30:08.4270,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,Subscriber,1976,1
15,191,2019-05-01 05:37:13.8920,2019-05-01 05:40:25.6140,3276,Marin Light Rail,40.714584,-74.042817,3186,Grove St PATH,40.719586,-74.043117,29577,Subscriber,1979,2
16,166,2019-05-01 05:41:10.7490,2019-05-01 05:43:57.6730,3267,Morris Canal,40.712419,-74.038526,3183,Exchange Place,40.716247,-74.033459,29550,Subscriber,1994,2
17,292,2019-05-01 05:42:31.6720,2019-05-01 05:47:24.1310,3677,Glenwood Ave,40.727551,-74.071061,3195,Sip Ave,40.730897,-74.063913,29668,Subscriber,1974,1
18,390,2019-05-01 05:45:03.7860,2019-05-01 05:51:34.5880,3209,Brunswick St,40.724176,-74.050656,3639,Harborside,40.719252,-74.034234,29297,Subscriber,1987,2
19,235,2019-05-01 05:51:16.2570,2019-05-01 05:55:11.4400,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,26200,Subscriber,1987,1
20,253,2019-05-01 05:53:33.2840,2019-05-01 05:57:46.5540,3214,Essex Light Rail,40.712774,-74.036486,3275,Columbus Drive,40.718355,-74.038914,29299,Subscriber,1983,2
21,358,2019-05-01 05:54:08.4790,2019-05-01 06:00:07.0700,3225,Baldwin at Montgomery,40.723659,-74.064194,3195,Sip Ave,40.730897,-74.063913,29612,Subscriber,1962,1
22,305,2019-05-01 05:57:32.5340,2019-05-01 06:02:38.1330,3203,Hamilton Park,40.727596,-74.044247,3639,Harborside,40.719252,-74.034234,29534,Subscriber,1964,1
23,220,2019-05-01 06:01:06.2950,2019-05-01 06:04:46.3050,3269,Brunswick & 6th,40.726012,-74.050389,3186,Grove St PATH,40.719586,-74.043117,26307,Subscriber,1989,2
24,287,2019-05-01 06:01:18.8850,2019-05-01 06:06:06.3640,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,26214,Subscriber,1967,1
25,188,2019-05-01 06:02:41.7050,2019-05-01 06:05:49.7330,3270,Jersey & 6th St,40.725289,-74.045572,3186,Grove St PATH,40.719586,-74.043117,29653,Subscriber,1976,1
26,124,2019-05-01 06:06:07.6050,2019-05-01 06:08:11.9590,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,28771,Subscriber,1982,1
27,193,2019-05-01 06:07:23.8650,2019-05-01 06:10:37.1990,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,29662,Subscriber,1992,1
28,83,2019-05-01 06:07:58.3730,2019-05-01 06:09:21.5580,3639,Harborside,40.719252,-74.034234,3183,Exchange Place,40.716247,-74.033459,29534,Subscriber,1988,1
29,248,2019-05-01 06:08:16.3530,2019-05-01 06:12:25.0170,3270,Jersey & 6th St,40.725289,-74.045572,3186,Grove St PATH,40.719586,-74.043117,29245,Subscriber,1981,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24880,5179,2018-11-09 13:05:22.0440,2018-11-09 14:31:41.7210,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29674,Subscriber,1974,1
24881,1386,2018-11-09 14:33:59.1640,2018-11-09 14:57:05.2150,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29674,Subscriber,1974,1
24882,16212,2018-11-12 12:58:18.9190,2018-11-12 17:28:31.2000,3694,Jackson Square,40.711130,-74.078900,3276,Marin Light Rail,40.714584,-74.042817,29677,Subscriber,1992,1
24883,604,2018-11-12 15:55:25.0370,2018-11-12 16:05:29.0630,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29618,Subscriber,1991,2
24884,1197,2018-11-13 16:38:49.4210,2018-11-13 16:58:46.9170,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,29582,Subscriber,1986,2
24885,1003,2018-11-14 06:23:56.6900,2018-11-14 06:40:40.5420,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29662,Subscriber,1977,1
24886,794,2018-11-14 16:13:19.6520,2018-11-14 16:26:34.4850,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29623,Subscriber,1986,2
24887,1336,2018-11-14 19:29:36.4350,2018-11-14 19:51:52.5900,3694,Jackson Square,40.711130,-74.078900,3202,Newport PATH,40.727224,-74.033759,29669,Customer,1989,1
24888,2517,2018-11-15 11:39:14.7350,2018-11-15 12:21:11.7570,3694,Jackson Square,40.711130,-74.078900,3192,Liberty Light Rail,40.711242,-74.055701,29494,Customer,1989,1
24889,597,2018-11-17 10:22:05.2810,2018-11-17 10:32:03.0190,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29441,Subscriber,1990,2
24890,1463,2018-11-17 14:39:55.2330,2018-11-17 15:04:18.3380,3694,Jackson Square,40.711130,-74.078900,3279,Dixon Mills,40.721630,-74.049968,29497,Subscriber,1988,2
24891,688,2018-11-17 18:33:03.6770,2018-11-17 18:44:31.6880,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29507,Subscriber,1991,2
24892,406,2018-11-18 13:04:14.7720,2018-11-18 13:11:01.0180,3694,Jackson Square,40.711130,-74.078900,3193,Lincoln Park,40.724605,-74.078406,29204,Subscriber,1990,2
24893,1405,2018-11-18 22:11:53.4960,2018-11-18 22:35:18.6370,3694,Jackson Square,40.711130,-74.078900,3220,5 Corners Library,40.734961,-74.059503,29244,Subscriber,1987,1
24894,673,2018-11-18 22:54:18.6150,2018-11-18 23:05:31.7600,3694,Jackson Square,40.711130,-74.078900,3677,Glenwood Ave,40.727551,-74.071061,29299,Customer,1998,2
24895,987,2018-11-20 06:27:14.2960,2018-11-20 06:43:41.6230,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29271,Subscriber,1977,1
24896,2023,2018-11-20 13:09:01.4580,2018-11-20 13:42:45.4240,3694,Jackson Square,40.711130,-74.078900,3184,Paulus Hook,40.714145,-74.033552,29652,Customer,1995,1
24897,943,2018-11-21 06:25:06.5540,2018-11-21 06:40:49.5850,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29458,Subscriber,1977,1
24898,872,2018-11-24 13:26:37.2970,2018-11-24 13:41:09.8250,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26193,Subscriber,1994,1
24899,673,2018-11-25 11:38:07.7060,2018-11-25 11:49:20.8900,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29439,Subscriber,1994,1
24900,1418,2018-11-26 09:55:15.2920,2018-11-26 10:18:54.0580,3694,Jackson Square,40.711130,-74.078900,3198,Heights Elevator,40.748716,-74.040443,29506,Customer,1987,1
24901,617,2018-11-26 10:24:41.1230,2018-11-26 10:34:58.5150,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26250,Subscriber,1994,1
24902,979,2018-11-26 22:09:13.7080,2018-11-26 22:25:32.7220,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29451,Customer,1987,1
24903,694,2018-11-27 12:06:57.5180,2018-11-27 12:18:32.5060,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29283,Subscriber,1994,1
24904,1013,2018-11-28 06:27:11.0670,2018-11-28 06:44:04.6710,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29538,Subscriber,1977,1
24905,734,2018-11-28 10:46:12.6640,2018-11-28 10:58:27.0750,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26255,Subscriber,1994,1
24906,312,2018-11-28 19:52:40.1140,2018-11-28 19:57:52.9270,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,29451,Subscriber,1957,1
24907,914,2018-11-29 10:20:57.7240,2018-11-29 10:36:12.0420,3694,Jackson Square,40.711130,-74.078900,3206,Hilltop,40.731169,-74.057574,29610,Subscriber,1994,1
24908,2392,2018-11-29 17:28:24.1590,2018-11-29 18:08:16.8720,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29659,Subscriber,1994,1
24909,637,2018-11-30 12:00:10.4100,2018-11-30 12:10:48.0210,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29536,Subscriber,1994,1

In [10]:
citibike_2018_2019.to_csv('citibike_2018_2019.csv', sep = ',')